SUPABASE_URL = "https://catsldxduvxagonxdwvs.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhdHNsZHhkdXZ4YWdvbnhkd3ZzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODYwNzcyMCwiZXhwIjoyMDc0MTgzNzIwfQ.zWb2c7HL6dRooGRMr16y2KxJQZb8TzhPf6JjtEcZagM"
